services:
  postgres: 
    image: postgres:latest
    container_name: teddy_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=teddy
      - POSTGRES_PASSWORD=teddy
      - POSTGRES_DB=teddy_db
